### ISSUE TITLE
Invalid memory address when starting Gauge plugin in IDEA

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/Intellij-Plugin#175]
When launching IDEA, I get the following error:

    Exception occurred in Gauge plugin: Please log an issue here with the following details and reload the project.
    ```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x20 pc=0x401c54]
    
    goroutine 1 [running]:
    panic(0xa77340, 0xc082002070)
      /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3f4
    main.main()
      /Users/stechops/Library/Application Support/Go Agent/pipelines/Gauge-Package/gauge-compile/gauge.go:152 +0xc14
    ```
    * Idea version: 2016.2
    * API version: IU-162.1121.32
    * Plugin version: 0.2.1
    * Gauge version: 0.5.0 (show balloon)

Of note, it looks like the error is pointing to an OS X user directory called `stechops`. I am on Windows, and this is not my username anyway.

### Information that will help us debug

* IntelliJ version and edition: IDEA 2016.2 Ultimate
* OS information: Windows 7 SP1
* Gauge IntelliJ plugin version. 0.2.1
* Does the project uses any Build tool(Gradle/Maven)? No
* Run gauge -v on your system and paste the results here.

Here are the results:

    Gauge version: 0.5.0
    
    Plugins
    -------
    html-report (2.1.0)
    java (0.4.0)
    xml-report (0.1.2)

**Comment by kashishm** [comment]
@Thunderforge Thanks for logging this issue. This is already fixed and available in the latest Gauge [nightly](https://bintray.com/gauge/Gauge/Nightly/_latestVersion). Could you please verify if it has fixed the issue? 
And the path you are seeing in the stack trace is of the machine where the binary was built.

**Comment by Thunderforge** [comment]
@kashishm Unfortunately, I still get an error, this time with less detail

    Exception occurred in Gauge plugin: Please log an issue here with the following details and reload the project.
    ```
    ```
    * Idea version: 2016.2
    * API version: IU-162.1121.32
    * Plugin version: 0.2.1
    * Gauge version: 0.5.1.nightly-2016-07-13 (show balloon)

**Comment by zahir033** [comment]
I am getting this error.

IDEA- 15.0.2
Gauge version: 0.5.0

Plugins
-------
html-report (2.1.0)
java (0.4.1)
xml-report (0.1.1)

**Comment by zahir033** [comment]
Can somebody fix the problem? I can't run any spec from IDEA.

**Comment by mahendrakariya** [comment]
@zahir033 We have released Gauge v0.6.0. Could you please [install the latest version](getgauge.io/get-started) and try again? Please ensure to run `gauge --update-all` after upgrading Gauge.

**Comment by zahir033** [comment]
No luck. Same issue.

Gauge version: 0.6.1

Plugins
-------
html-report (2.1.1)
java (0.5.0)
xml-report (0.1.3)

Gauge IDEA plugin : 0.2.1
IDEA version:  2016.1.3

**Comment by barrysvee** [comment]
No luck here, either.

**Comment by barrysvee** [comment]
Speaking with others around the office it's not the version of gauge or the IDEA plugin but the version of IDEA. Those running IDEA 15.0.x have no problems. I recall that the plugin worked in at least IDEA 2016.0 but somewhere in the 2016.1.x the plugin broke and remains broken. It sounds like JetBrains broke a ton of other plugins recently.

**Comment by Thunderforge** [comment]
I am running 2016.2.x and see the issue too.

**Comment by kashishm** [comment]
I have pushed a commit which addresses the issue. Could you please try to install the [latest](https://bintray.com/gauge/Gauge-Java-Intellij/Nightly) nightly version of the plugin and see if the issue still exists?

**Comment by madhura-optymyze** [comment]
Finally, it's working!! Thanks a lot @kashishm

**Comment by zahir033** [comment]
I upgraded my Intellij to 2016.2.2 and even it is still an issue for me. Now giving the below fatal exception 

com.intellij.openapi.module.impl.ModuleManagerComponent@6e864f: Gauge API not started
java.lang.RuntimeException: Gauge API not started
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:50)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.<init>(GaugeConnection.java:40)
	at com.thoughtworks.gauge.GaugeModuleComponent.initializeGaugeConnection(GaugeModuleComponent.java:100)
	at com.thoughtworks.gauge.GaugeModuleComponent.createGaugeService(GaugeModuleComponent.java:92)
	at com.thoughtworks.gauge.module.lib.AbstractLibHelper.<init>(AbstractLibHelper.java:37)
	at com.thoughtworks.gauge.module.lib.GaugeLibHelper.<init>(GaugeLibHelper.java:51)
	at com.thoughtworks.gauge.module.lib.LibHelperFactory.helperFor(LibHelperFactory.java:35)
	at com.thoughtworks.gauge.GaugeModuleComponent.projectOpened(GaugeModuleComponent.java:66)
	at com.thoughtworks.gauge.GaugeModuleComponent.moduleAdded(GaugeModuleComponent.java:80)
	at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:208)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.c(ModuleManagerImpl.java:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAddedInWriteAction(ModuleManagerImpl.java:570)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.a(ModuleManagerComponent.java:125)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.fireModulesAdded(ModuleManagerComponent.java:125)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.projectOpened(ModuleManagerImpl.java:558)
	at com.intellij.openapi.project.impl.ProjectImpl.b(ProjectImpl.java:383)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:68)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:418)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:91)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.i(ProjectManagerImpl.java:655)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.c(ProjectManagerImpl.java:329)
	at com.intellij.openapi.application.TransactionGuardImpl$3.run(TransactionGuardImpl.java:168)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:455)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1665)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1607)
	at com.intellij.openapi.progress.util.ProgressDialog.show(ProgressDialog.java:317)
	at com.intellij.openapi.progress.util.ProgressWindow.showDialog(ProgressWindow.java:235)
	at com.intellij.openapi.progress.util.ProgressWindow$2.a(ProgressWindow.java:180)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:950)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:570)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:396)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:312)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:191)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:402)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:187)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:605)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:639)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:377)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy47.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:343)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:341)
	at com.intellij.idea.IdeaApplication.c(IdeaApplication.java:196)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kashishm** [comment]
@zahir033 Does your project uses any build tool? If yes, please share the screenshot of IntelliJ modules structure for the project.(`File -> Project Structure -> Modules tab`)

Can you try running the specs from the command line for the same project. For a Gradle-Gauge project, use `gradle gauge`, for a Maven project, use `mvn test`, for normal Gauge project, use `gauge specs` command to run the spec and send us the output if it errors out.

**Comment by pradnyasamant** [comment]
I am facing the same issue when a new spec folder is cloned and idea is launched later.

Version
Idea 2016.2.2
Gauge: 0.2.3
Plugin: 0.5.0

**Comment by pradnyasamant** [comment]
Please note that the project works perfect on a new setup ( or reclone once the problem starts occurring). the problem occurs only when folders spec is/are added and intellij is launched after adding those folders.
This is specific to gauge-java plugin and intellij version as per my observation

**Comment by pradnyasamant** [comment]
We keep some .gradle files too inside the specs. (Project is java, not using it as a gradle project) Can that be an issue?

I changed the path of specs folder to ..GaugeProject\src\specs\<spec1Folder1>, <SpecFolder2>, this fashion and the issue does not reproduce with this structure.

Successfully fixed this for some other colleagues as well.

Also another observation is - this issue does not appear on 32 bit machines.

**Comment by saritapol13** [comment]
The solution mentioned by @pradnyasamant  is working and solving the issue

**Comment by mahendrakariya** [comment]
@Thunderforge Just want to check if you are still facing this issue?

**Comment by pradnyasamant** [comment]
Yes, we would face the issue still if we use the default folder structure .

Moving the specs folder solves the problem

**Comment by Thunderforge** [comment]
Still having the problem. Running Intellij IDEA 2016.2.4 and the Gauge IDEA plugin 0.2.3.

    com.intellij.openapi.module.impl.ModuleManagerComponent@2b2e0716: Gauge API not started
	java.lang.RuntimeException: Gauge API not started
		at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:50)
		at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
		at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
		at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
		at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
		at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
		at com.thoughtworks.gauge.GaugeConnection.<init>(GaugeConnection.java:40)
		at com.thoughtworks.gauge.GaugeModuleComponent.initializeGaugeConnection(GaugeModuleComponent.java:100)
		at com.thoughtworks.gauge.GaugeModuleComponent.createGaugeService(GaugeModuleComponent.java:92)
		at com.thoughtworks.gauge.module.lib.GaugeLibHelper.gaugeLib(GaugeLibHelper.java:164)
		at com.thoughtworks.gauge.module.lib.GaugeLibHelper.updateGaugeJavaLibIfNeeded(GaugeLibHelper.java:109)
		at com.thoughtworks.gauge.module.lib.GaugeLibHelper.checkDeps(GaugeLibHelper.java:59)
		at com.thoughtworks.gauge.GaugeModuleComponent.projectOpened(GaugeModuleComponent.java:66)
		at com.thoughtworks.gauge.GaugeModuleComponent.moduleAdded(GaugeModuleComponent.java:80)
		at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:208)
		at com.intellij.openapi.module.impl.ModuleManagerImpl.d(ModuleManagerImpl.java:571)
		at com.intellij.openapi.module.impl.ModuleManagerImpl$$Lambda$297/1132019774.run(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:898)
		at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAddedInWriteAction(ModuleManagerImpl.java:570)
		at com.intellij.openapi.module.impl.ModuleManagerComponent.a(ModuleManagerComponent.java:125)
		at com.intellij.openapi.module.impl.ModuleManagerComponent$$Lambda$296/424231819.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
		at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
		at com.intellij.openapi.module.impl.ModuleManagerComponent.fireModulesAdded(ModuleManagerComponent.java:125)
		at com.intellij.openapi.module.impl.ModuleManagerImpl.projectOpened(ModuleManagerImpl.java:558)
		at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:383)
		at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:68)
		at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:418)
		at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:91)
		at com.intellij.openapi.project.impl.ProjectManagerImpl.e(ProjectManagerImpl.java:655)
		at com.intellij.openapi.project.impl.ProjectManagerImpl.c(ProjectManagerImpl.java:329)
		at com.intellij.openapi.project.impl.ProjectManagerImpl$$Lambda$281/1338225940.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl$3.run(TransactionGuardImpl.java:168)
		at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
		at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
		at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
		at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
		at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
		at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
		at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:793)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
		at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
		at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
		at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
		at java.awt.Dialog.show(Dialog.java:1084)
		at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
		at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:455)
		at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1665)
		at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1607)
		at com.intellij.openapi.progress.util.ProgressDialog.show(ProgressDialog.java:317)
		at com.intellij.openapi.progress.util.ProgressWindow.showDialog(ProgressWindow.java:235)
		at com.intellij.openapi.progress.util.ProgressWindow$2.a(ProgressWindow.java:180)
		at com.intellij.openapi.progress.util.ProgressWindow$2$$Lambda$192/1126771694.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
		at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
		at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
		at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
		at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:793)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
		at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:880)
		at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
		at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
		at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:562)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:396)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
		at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:312)
		at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:192)
		at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:402)
		at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:187)
		at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
		at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:605)
		at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:639)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
		at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:377)
		at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
		at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:343)
		at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
		at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
		at com.sun.proxy.$Proxy46.appStarting(Unknown Source)
		at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:343)
		at com.intellij.idea.IdeaApplication$IdeStarter$$Lambda$173/1335530829.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
		at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
		at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
		at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
		at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
		at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:341)
		at com.intellij.idea.IdeaApplication.a(IdeaApplication.java:196)
		at com.intellij.idea.IdeaApplication$$Lambda$151/1817030190.run(Unknown Source)
		at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
		at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:196)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:62)
		at com.intellij.idea.MainImpl$1$1$$Lambda$52/1559704997.run(Unknown Source)
		at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kashishm** [comment]
@Thunderforge Do you see any other exception with the following message
```
Exception occurred in Gauge plugin: Please log an issue here with the following details...
```
If yes, please send us the whole stack trace of the above exception? This can help us debug the issue.

**Comment by ocary** [comment]
The original problem was **solved** by making sure all Gauge projects had _manifest.json_.  We had two Gauge subprojects used as step reference modules for common fixtures that were missing this file..

Basic structure:
- AReferenceGaugeProject
- BProject
- CProject
- DProject
- YReferenceGaugeProject

B, C, and D projects had A and/or Y as reference modules.   A and Y didn't have any specs in them, just step definitions and other utility code used in B, C, and/or D.   A and Y didn't have _manifest.json_.

Adding _manifest.json_ with the same content as BProject got rid of the _invalid memory address or nil pointer reference_ exception.

Adding _manifest.json_ also got rid of the problem where, sometimes, all steps in a spec were shown as "undefined step" and underlined in red in IntelliJ.  Gauge would still execute the specs as expected, but IntelliJ + Gauge were having issues; underlined and couldn't click-navigate to the step definition,


Error message
Exception occurred in Gauge plugin: Please log an issue here with the following details and reload the project.
					```
					panic: runtime error: invalid memory address or nil pointer dereference
					[signal 0xc0000005 code=0x0 addr=0x20 pc=0x401c54]
					
					goroutine 1 [running]:
					panic(0xa77340, 0xc0820020e0)
						/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3f4
					main.main()
						/Users/stechops/Library/Application Support/Go Agent/pipelines/Gauge-Package/gauge-compile/gauge.go:152 +0xc14
					```
					* Idea version: 2016.2.4
					* API version: IU-162.2032.8
					* Plugin version: 0.2.3
					* Gauge version: 0.5.0

**Comment by ocary** [comment]
Also, if the overall project structure is valid and adding _manifest.json_ was the right thing to do, then having a "file not found" type of error message rather than invalid memory error would be really nice.

**Comment by Thunderforge** [comment]
@kashishm This problem was taken over by @ocary and I have no longer been working on this issue. It seems like he identified the problem as a missing `manifest.json` problem. If that could be fixed so that we don't have a memory error if that file is missing, I would be obliged.
