### ISSUE TITLE
Gauge plugin errors on IDEA 2016 startup

### ISSUE THREAD

**Issue by barrysvee** [getgauge/Intellij-Plugin#177]
### Expected behavior

Tell us what should happen

IDEA should not show errors with Gauge initialization upon startup.
### Actual behavior

Tell us what happens instead

Both IDEA 2016.1 and .2 display error upon startup with Gauge plugin.
### Steps to reproduce
1. Launch IDEA
   2.
   3.
### Information that will help us debug
- Idea version: 2016.2.1
- API version: IU-162.1447.26
- Plugin version: 0.2.1
- Gauge version: 0.6.1
- IntelliJ version and edition(Community/Ultimate)
- OS information OS X 10.10
- Gauge IntelliJ plugin version. 0.2.1
- Does the project uses any Build tool(Gradle/Maven)? Gradle
- Run gauge -v on your system and paste the results here.

Gauge version: 0.6.1
## Plugins

html-report (2.1.1)
java (0.5.0)
xml-report (0.1.3)
## Stack Trace

```
2016-08-08 09:47:44,706 [   8317]   INFO - ellij.project.impl.ProjectImpl - 188 project components initialized in 2047 ms 
2016-08-08 09:47:45,023 [   8634]   INFO - le.impl.ModuleManagerComponent - 19 module(s) loaded in 316 ms 
2016-08-08 09:47:45,488 [   9099]   INFO - m.thoughtworks.gauge.GaugeUtil - PATH => /Library/Frameworks/Python.framework/Versions/3.4/bin:/Users/sveebr/dev/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin:/Users/sveebr/dev/bin/apache/apache-ant-1.9.4/bin:/usr/local/bin/python3:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/munki::/Users/sveebr/dev/xcode/depot_tools 
2016-08-08 09:47:45,488 [   9099]   INFO - m.thoughtworks.gauge.GaugeUtil - GAUGE_ROOT => null 
2016-08-08 09:47:45,490 [   9101]   INFO - m.thoughtworks.gauge.GaugeUtil - executable path: /usr/local/bin/gauge 
2016-08-08 09:47:50,523 [  14134]  ERROR - ellij.project.impl.ProjectImpl - com.intellij.openapi.module.impl.ModuleManagerComponent@63aed345 
java.lang.RuntimeException: Gauge API not started
    at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:50)
    at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
    at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
    at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
    at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
    at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
    at com.thoughtworks.gauge.GaugeConnection.<init>(GaugeConnection.java:40)
    at com.thoughtworks.gauge.GaugeModuleComponent.initializeGaugeConnection(GaugeModuleComponent.java:100)
    at com.thoughtworks.gauge.GaugeModuleComponent.createGaugeService(GaugeModuleComponent.java:92)
    at com.thoughtworks.gauge.module.lib.GaugeLibHelper.gaugeLib(GaugeLibHelper.java:170)
    at com.thoughtworks.gauge.module.lib.GaugeLibHelper.updateGaugeJavaLibIfNeeded(GaugeLibHelper.java:115)
    at com.thoughtworks.gauge.module.lib.GaugeLibHelper.checkDeps(GaugeLibHelper.java:61)
    at com.thoughtworks.gauge.GaugeModuleComponent.projectOpened(GaugeModuleComponent.java:66)
    at com.thoughtworks.gauge.GaugeModuleComponent.moduleAdded(GaugeModuleComponent.java:80)
    at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:208)
    at com.intellij.openapi.module.impl.ModuleManagerImpl.a(ModuleManagerImpl.java:571)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
    at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAddedInWriteAction(ModuleManagerImpl.java:570)
    at com.intellij.openapi.module.impl.ModuleManagerComponent.d(ModuleManagerComponent.java:125)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
    at com.intellij.openapi.module.impl.ModuleManagerComponent.fireModulesAdded(ModuleManagerComponent.java:125)
    at com.intellij.openapi.module.impl.ModuleManagerImpl.projectOpened(ModuleManagerImpl.java:558)
    at com.intellij.openapi.project.impl.ProjectImpl.a(ProjectImpl.java:381)
    at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:68)
    at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:416)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:91)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.e(ProjectManagerImpl.java:655)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:329)
    at com.intellij.openapi.application.TransactionGuardImpl$3.run(TransactionGuardImpl.java:168)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
    at java.awt.Dialog.show(Dialog.java:1084)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:455)
    at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1665)
    at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1607)
    at com.intellij.openapi.progress.util.ProgressDialog.show(ProgressDialog.java:317)
    at com.intellij.openapi.progress.util.ProgressWindow.showDialog(ProgressWindow.java:235)
    at com.intellij.openapi.progress.util.ProgressWindow$2.a(ProgressWindow.java:180)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:950)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
    at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:570)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:396)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
    at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:312)
    at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:191)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:402)
    at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:187)
    at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
    at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:605)
    at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:639)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:377)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:343)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
    at com.sun.proxy.$Proxy47.appStarting(Unknown Source)
    at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:343)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
    at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
    at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:341)
    at com.intellij.idea.IdeaApplication.c(IdeaApplication.java:196)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2016-08-08 09:47:50,529 [  14140]  ERROR - ellij.project.impl.ProjectImpl - IntelliJ IDEA 2016.2.1  Build #IU-162.1447.26 
2016-08-08 09:47:50,529 [  14140]  ERROR - ellij.project.impl.ProjectImpl - JDK: 1.8.0_76-release 
2016-08-08 09:47:50,529 [  14140]  ERROR - ellij.project.impl.ProjectImpl - VM: OpenJDK 64-Bit Server VM 
2016-08-08 09:47:50,529 [  14140]  ERROR - ellij.project.impl.ProjectImpl - Vendor: JetBrains s.r.o 
2016-08-08 09:47:50,529 [  14140]  ERROR - ellij.project.impl.ProjectImpl - OS: Mac OS X 
2016-08-08 09:47:50,529 [  14140]  ERROR - ellij.project.impl.ProjectImpl - Last Action:  
2016-08-08 09:47:53,108 [  16719]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 710ms; general responsiveness: ok; EDT responsiveness: ok 
2016-08-08 09:47:56,063 [  19674]   INFO - tartup.impl.StartupManagerImpl - /Users/sveebr/dev/apps/AthenaBrowser/main/.idea case-sensitivity: expected=false actual=false 
2016-08-08 09:47:58,686 [  22297]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 16072 ms 
2016-08-08 09:48:11,309 [  34920]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 18200ms; general responsiveness: ok; EDT responsiveness: 1/19 sluggish, 1/19 very slow 
2016-08-08 09:48:11,332 [  34943]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 156735 files to update 
2016-08-08 09:48:25,969 [  49580]   INFO - rforceReadOnlyFileStateManager - --- recheck missing 
2016-08-08 09:49:43,065 [ 126676]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 91733ms; general responsiveness: ok; EDT responsiveness: 1/91 sluggish 
2016-08-08 09:51:02,917 [ 206528]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2016-08-08 09:51:03,061 [ 206672]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2016-08-08 09:51:03,313 [ 206924]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 139ms; general responsiveness: ok; EDT responsiveness: ok 
2016-08-08 09:51:04,309 [ 207920]   INFO - rforceReadOnlyFileStateManager - --- recheck missing 
2016-08-08 09:51:07,544 [ 211155]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 4230ms; general responsiveness: ok; EDT responsiveness: ok 
2016-08-08 09:51:13,001 [ 216612]   WARN - rationStore.ComponentStoreImpl -  
com.intellij.configurationStore.ReadOnlyModificationException
    at com.intellij.configurationStore.FileBasedStorageKt.a(FileBasedStorage.kt:203)
    at com.intellij.configurationStore.FileBasedStorageKt.writeFile(FileBasedStorage.kt:171)
    at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.saveLocally(FileBasedStorage.kt:96)
    at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.kt:147)
    at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.save(FileBasedStorage.kt:81)
    at com.intellij.configurationStore.ComponentStoreImplKt.executeSave(ComponentStoreImpl.kt:446)
    at com.intellij.configurationStore.ComponentStoreImpl.doSave(ComponentStoreImpl.kt:217)
    at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:164)
    at com.intellij.configurationStore.ProjectWithModulesStoreImpl.beforeSave(ProjectStoreImpl.kt:344)
    at com.intellij.configurationStore.ProjectStoreImpl.doSave(ProjectStoreImpl.kt:285)
    at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:164)
    at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:49)
    at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:341)
    at com.intellij.ide.SaveAndSyncHandlerImpl.doSaveDocumentsAndProjectsAndApp(SaveAndSyncHandlerImpl.java:137)
    at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:125)
    at com.intellij.ide.SaveAndSyncHandlerImpl$2.a(SaveAndSyncHandlerImpl.java:94)
    at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
    at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
    at com.intellij.ide.SaveAndSyncHandlerImpl$2.onFrameDeactivated(SaveAndSyncHandlerImpl.java:92)
    at com.intellij.ide.FrameStateManagerImpl.b(FrameStateManagerImpl.java:84)
    at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
    at com.intellij.ide.FrameStateManagerImpl$2.a(FrameStateManagerImpl.java:70)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by BugDiver** [comment]
@barrysvee  could you please try to install [nightly](gauge-java-intellij-0.2.2.nightly-2016-08-10.zip) version of the plugin and see if the issue still exists.

**Comment by barrysvee** [comment]
No luck with the download.

This site can’t be reached

*gauge-java-intellij-0.2.2.nightly-2016-08-10.zip* took too long to respond.


   - Search Google for gauge java intellij nightly 2016 zip
   <https://www.google.com/search?q=gauge%20java%20intellij%20nightly%202016%20zip>

ERR_CONNECTION_TIMED_OUT

**Comment by mahendrakariya** [comment]
Could you please download the jar file from [here](https://bintray.com/gauge/Gauge-Java-Intellij/Nightly/0.2.2.nightly-2016-08-10) and try installing the plugin manually?

**Comment by barrysvee** [comment]
I uninstalled the plugin, restarted idea, and manually installed the nightly build per these instructions: https://www.jetbrains.com/help/idea/2016.2/installing-plugin-from-disk.html. Still no luck.

Please log an issue here with the following details and reload the project.
```
```
* Idea version: 2016.2.1
* API version: IU-162.1447.26
* Plugin version: 0.2.2
* Gauge version: 0.6.1

```
2016-08-10 09:25:52,389 [   7206]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@2516b441 
2016-08-10 09:25:52,795 [   7612]   INFO - ction.BrowserConnectionManager - Browser connected: version 2.0.9, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36 
2016-08-10 09:25:52,845 [   7662]   INFO - CompilerWorkspaceConfiguration - Available processors: 8 
2016-08-10 09:25:54,139 [   8956]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.search.SearchableOptionPreloader@52576bbf 
2016-08-10 09:25:54,586 [   9403]   INFO - ellij.project.impl.ProjectImpl - 188 project components initialized in 2222 ms 
2016-08-10 09:25:54,896 [   9713]   INFO - le.impl.ModuleManagerComponent - 19 module(s) loaded in 309 ms 
2016-08-10 09:25:55,272 [  10089]   INFO - m.thoughtworks.gauge.GaugeUtil - PATH => /Library/Frameworks/Python.framework/Versions/3.4/bin:/Users/sveebr/dev/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin:/Users/sveebr/dev/bin/apache/apache-ant-1.9.4/bin:/usr/local/bin/python3:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/munki::/Users/sveebr/dev/xcode/depot_tools 
2016-08-10 09:25:55,272 [  10089]   INFO - m.thoughtworks.gauge.GaugeUtil - GAUGE_ROOT => null 
2016-08-10 09:25:55,274 [  10091]   INFO - m.thoughtworks.gauge.GaugeUtil - executable path: /usr/local/bin/gauge 
2016-08-10 09:26:00,308 [  15125]  ERROR - ellij.project.impl.ProjectImpl - com.intellij.openapi.module.impl.ModuleManagerComponent@50c102ba 
java.lang.RuntimeException: Gauge API not started
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:50)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.<init>(GaugeConnection.java:40)
	at com.thoughtworks.gauge.GaugeModuleComponent.initializeGaugeConnection(GaugeModuleComponent.java:100)
	at com.thoughtworks.gauge.GaugeModuleComponent.createGaugeService(GaugeModuleComponent.java:92)
	at com.thoughtworks.gauge.module.lib.GaugeLibHelper.gaugeLib(GaugeLibHelper.java:164)
	at com.thoughtworks.gauge.module.lib.GaugeLibHelper.updateGaugeJavaLibIfNeeded(GaugeLibHelper.java:109)
	at com.thoughtworks.gauge.module.lib.GaugeLibHelper.checkDeps(GaugeLibHelper.java:59)
	at com.thoughtworks.gauge.GaugeModuleComponent.projectOpened(GaugeModuleComponent.java:66)
	at com.thoughtworks.gauge.GaugeModuleComponent.moduleAdded(GaugeModuleComponent.java:80)
	at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:208)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.a(ModuleManagerImpl.java:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAddedInWriteAction(ModuleManagerImpl.java:570)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.d(ModuleManagerComponent.java:125)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.fireModulesAdded(ModuleManagerComponent.java:125)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.projectOpened(ModuleManagerImpl.java:558)
	at com.intellij.openapi.project.impl.ProjectImpl.a(ProjectImpl.java:381)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:68)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:416)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:91)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.e(ProjectManagerImpl.java:655)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:329)
	at com.intellij.openapi.application.TransactionGuardImpl$3.run(TransactionGuardImpl.java:168)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:455)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1665)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1607)
	at com.intellij.openapi.progress.util.ProgressDialog.show(ProgressDialog.java:317)
	at com.intellij.openapi.progress.util.ProgressWindow.showDialog(ProgressWindow.java:235)
	at com.intellij.openapi.progress.util.ProgressWindow$2.a(ProgressWindow.java:180)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:950)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:570)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:396)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:312)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:191)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:402)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:187)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:605)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:639)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:377)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy47.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:343)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:341)
	at com.intellij.idea.IdeaApplication.c(IdeaApplication.java:196)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2016-08-10 09:26:00,314 [  15131]  ERROR - ellij.project.impl.ProjectImpl - IntelliJ IDEA 2016.2.1  Build #IU-162.1447.26 
2016-08-10 09:26:00,314 [  15131]  ERROR - ellij.project.impl.ProjectImpl - JDK: 1.8.0_76-release 
2016-08-10 09:26:00,314 [  15131]  ERROR - ellij.project.impl.ProjectImpl - VM: OpenJDK 64-Bit Server VM 
2016-08-10 09:26:00,314 [  15131]  ERROR - ellij.project.impl.ProjectImpl - Vendor: JetBrains s.r.o 
2016-08-10 09:26:00,314 [  15131]  ERROR - ellij.project.impl.ProjectImpl - OS: Mac OS X 
2016-08-10 09:26:00,314 [  15131]  ERROR - ellij.project.impl.ProjectImpl - Last Action:  
2016-08-10 09:26:03,588 [  18405]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 1226ms; general responsiveness: ok; EDT responsiveness: ok 
```

**Comment by kashishm** [comment]
@barrysvee Could you please share the project/modules structure(`File | Project Structure | Modules` in IntelliJ) and logs present in `logs` directory of gauge project.

It would be really helpful if you could send us a sample project which has this issue.

**Comment by madhura-optymyze** [comment]
I'm facing the same issue inspite of using 0.2.2.nightly-2016-08-12.

**Comment by kashishm** [comment]
@madhura-optymyze @barrysvee Can you try running the specs from the command line for the same project. For a Gradle-Gauge project, use `gradle gauge`, for a Maven project, use `mvn test`, for normal Gauge project, use `gauge specs` command to run the spec and send us the output if it errors out.

**Comment by madhura-optymyze** [comment]
my issue was fixed with the latest nightly build.. no more errors :)

**Comment by barrysvee** [comment]
I still have an error on startup with the 8-29 build. Note that Gauge has no issues when running from the command line.

`Gauge version: 0.6.1

Plugins
-------
html-report (2.1.1)
java (0.5.0)
xml-report (0.1.3)`

`com.intellij.openapi.module.impl.ModuleManagerComponent@6a9a51f3: Gauge API not started
java.lang.RuntimeException: Gauge API not started
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:50)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.<init>(GaugeConnection.java:40)
	at com.thoughtworks.gauge.GaugeModuleComponent.initializeGaugeConnection(GaugeModuleComponent.java:100)
	at com.thoughtworks.gauge.GaugeModuleComponent.createGaugeService(GaugeModuleComponent.java:92)
	at com.thoughtworks.gauge.module.lib.GaugeLibHelper.gaugeLib(GaugeLibHelper.java:164)
	at com.thoughtworks.gauge.module.lib.GaugeLibHelper.updateGaugeJavaLibIfNeeded(GaugeLibHelper.java:109)
	at com.thoughtworks.gauge.module.lib.GaugeLibHelper.checkDeps(GaugeLibHelper.java:59)
	at com.thoughtworks.gauge.GaugeModuleComponent.projectOpened(GaugeModuleComponent.java:66)
	at com.thoughtworks.gauge.GaugeModuleComponent.moduleAdded(GaugeModuleComponent.java:80)
	at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:208)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.c(ModuleManagerImpl.java:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAddedInWriteAction(ModuleManagerImpl.java:570)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.a(ModuleManagerComponent.java:125)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.fireModulesAdded(ModuleManagerComponent.java:125)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.projectOpened(ModuleManagerImpl.java:558)
	at com.intellij.openapi.project.impl.ProjectImpl.b(ProjectImpl.java:383)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:68)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:418)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:91)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.i(ProjectManagerImpl.java:655)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.c(ProjectManagerImpl.java:329)
	at com.intellij.openapi.application.TransactionGuardImpl$3.run(TransactionGuardImpl.java:168)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:455)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1665)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1607)
	at com.intellij.openapi.progress.util.ProgressDialog.show(ProgressDialog.java:317)
	at com.intellij.openapi.progress.util.ProgressWindow.showDialog(ProgressWindow.java:235)
	at com.intellij.openapi.progress.util.ProgressWindow$2.a(ProgressWindow.java:180)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:950)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:570)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:396)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:312)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:191)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:402)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:187)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:605)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:639)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:377)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy48.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter.a(IdeaApplication.java:343)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:341)
	at com.intellij.idea.IdeaApplication.c(IdeaApplication.java:196)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by poddarsneha** [comment]
I am also facing similar issue on Idea startup
Idea - 2016.2.2
I have installed idea gauge plugin-  0.2.3
Gauge version: 0.6.1
Plugins
-------
html-report (2.1.1)
java (0.5.0)

The error comes as "com.intellij.openapi.module.impl.ModuleManagerComponent@5d634413: Gauge API not started"
and the specs are red with error "Steps not implemented"
Inspite of the errors, I am able to execute the specs. 

Is there any way I can resolve the issue?

**Comment by kashishm** [comment]
@barrysvee @poddarsneha please share the screenshot of IntelliJ modules structure for the project.(`File -> Project Structure -> Modules tab`)

**Comment by poddarsneha** [comment]
@kashishm - Sharing the module structure of the project. 
![gaugeproject](https://cloud.githubusercontent.com/assets/10878188/18265067/71ba2292-7431-11e6-97a4-33ba3859dd83.JPG)

**Comment by kashishm** [comment]
@poddarsneha can you close the project, delete `.idea/` folder and `*.iml` files, and open the project again.

**Comment by poddarsneha** [comment]
@kashishm - Deleting the .idea folder and reopening the project worked :).. 
Thank you!!

**Comment by barrysvee** [comment]
Many of the configurations in our .idea folder are checked into version
control and used by developers and CI. Wiping out this folder is not an
option. Can you be more specific about which files or entries within them
require surgery to fix the issue?

**Comment by kashishm** [comment]
Gradle project/module structure has been changed in IntelliJ 2016.1 and above. Each source set of a Gradle project is now a separate module in the IDE – and may have its own dependencies. Refer [this](https://blog.jetbrains.com/idea/2016/03/intellij-idea-2016-1-is-here/) blog for more info.

Unfortunately, It's difficult for us to exactly point out the changes that you need to do as it depends on the individual project. Since you have checked in your `.idea` folder, we recommend you to delete the folder once, reopen the project, see the diff and commit / checkout the changes according to your needs.

You can open [this](https://github.com/getgauge/gauge-example-java) Gauge Gradle project in Intellij and refer its `.idea` folder for changes.

**Comment by mahendrakariya** [comment]
@barrysvee Are you still facing this issue?

**Comment by barrysvee** [comment]
Yes, many of us on the team have abandoned running Gauge within IDEA. Some
have chosen to stay with IDEA 15 instead of upgrading to 2016.

Our project has two "commons" IDEA modules shared between multiple Gauge
test modules. I've been told that intellisense works after removing the
shared modules, although with the dependencies gone they won't run.

**Comment by ocary** [comment]
Update:  Myself and others are currently testing a fix for the above problem.  Unfortunately @barrysvee has left our company, so he won't be one of the people testing this fix.

The error ```
java.lang.RuntimeException: Gauge API not started
    at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:50)
``` is not seen after updating the plugin with the code below.   This was off of the latest plugin code (Oct 26, 2017.   v2.4),.

The updated plugin has been tested so far on a couple different versions of Gauge and related plugins including
-  Win10 + IntelliJ 2016.2.5 + Java 1.8.0_111 + 0.6.3.nightly-2016-10-25 +gauge-java 0.5.0
- Win7 + Java 1..8.0_101+ IntelliJ 2016.2.4 + 0.5.0 + gauge-java 0.4.1

After installing the updated plugin, looking in the _idea.log_ file there are sometimes messages (log message from the new code): _Unable to open connection on try N.   Waiting and trying again_   Sometimes there are none, on some systems there is usually one 1, and on some systems there are typically 2 messages.   The pattern of slower systems have more of these messages, though so far I have not seen the counter get above 2 or 3, but have not checked it on very slow and underpowered machines.

A "better" fix might be making the createConnection(5) call in GaugeConnection.class something larger - maybe 60? - but as that source is further down in gaugert.0.0.2.jar, I have not implemented that to test to see if it also fixes the issue.


Replacement code used for initializeGaugeConnection(int apiPort)
  ```
  private static GaugeConnection initializeGaugeConnection(int apiPort) {
        if (apiPort != -1) {
            LOG.warn("Initializing Gauge connection");
            GaugeConnection gaugeConn = null;

            for (int i = 1; i <= 10; i++) {
                try {
                    gaugeConn = new GaugeConnection(apiPort);
                    break;
                } catch (java.lang.RuntimeException ex) {
                    LOG.warn("Unable to open connection on try " + i + ".   Waiting and trying again");
                    try {
                        Thread.sleep(5000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }

            return gaugeConn;
        } else {
            return null;
        }
    }

```

**Comment by diana-zaharia** [comment]
@kashishm @mahendrakariya is there any chance the fix mentioned by @ocary is included in any future releases? The fix has been working for us, we have a large no. of specs and we need a bigger timeout or a retry mechanism before erroring on create connection. We are currently patching every new release of the gauge intellij plugin and as you can imagine it is becoming quite tedious. Thanks!

**Comment by nehashri** [comment]
@diana-zaharia have you tried with the latest intellij plugin, without your changes? There are a few changes that has been done on Intellij-Plugin that doesn't require such a long time for Gauge to connect. Please check with the latest version of Intellij-Plugin and let us know if you are still facing this issue.

**Comment by diana-zaharia** [comment]
@nehashri Unfortunately yes, it's still erroring out using latest Gauge Intellij Plugin 0.3.9.

**Comment by nehashri** [comment]
@diana-zaharia We currently do not have plans to change the Intellij Plugin. But we would be happy to accept a Pull request which fixes the above issue. If you would like to contribute, please raise a pull request with the changes that work for you.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
