### ISSUE TITLE
Plugin build not reproducible

### ISSUE THREAD

**Issue by ginkel** [getgauge/Intellij-Plugin#374]
Attempting to build the Gauge IntelliJ plugin from source (both from `master` as well as from the `v0.3.14` tag) currently fails as the plugin declares the `com.thoughtworks.gauge:gauge-java` without specifying a version number:

```
dependencies {
    compile(
            'com.thoughtworks.gauge:gauge-java:+',
    )
    testCompile(
            'org.mockito:mockito-all:1.10.19',
    )
}
```

This causes the build of the plugin to fail as `gauge-java` apparently changed in an incompatible fashion (due to the constant `com.thoughtworks.gauge.GaugeConstant.GAUGE_DEBUG_OPTS_ENV` being removed).

I'd propose to specify an exact dependency version for all dependencies in order to achieve reproducible builds.

**Comment by nehashri** [comment]
@ginkel Sorry about this. We will fix this soon. This should ideally have been backward compatible, but it has been removed accidentally.

**Comment by nehashri** [comment]
I have pushed in changes to fix the build. Please check

**Comment by ginkel** [comment]
Thanks, @nehashri!

While this technically solves the broken build, the build is still not reproducible as updates to `gauge-java` will actually cause a different plugin being built despite the plugin version number staying the same. In my experience this is very unusual in the Java world although Maven and Gradle provide an option to reference version ranges.

What do you think?

**Comment by nehashri** [comment]
@ginkel The fixes I have pushed are temporary. And yes, for most projects you may not want to have a floating version specified. But this is not unusual in the Gradle world. Gradle itself recommends this approach in some cases (https://docs.gradle.org/current/userguide/declaring_dependencies.html#declaring_a_dependency_without_version).
The reason we have a floating version number is because the IntelliJ plugin doesn't go through as much changes as gauge-java. We would like to have the latest version of gauge-java for IntelliJ. It is not possible to release a new version of IntelliJ for every gauge-java release.
 Also, we try to maintain backward compatibility in gauge-java as much as possible. This is one time we have missed this, we will be doing a release of IntelliJ to fix this soon.
